using System;

namespace problem2
{
    class Program
    {
        static void Main(string[] args)
        {
            /*
             Project Euler Problem 2 
                EN: Each new term in the Fibonacci sequence is generated by adding the previous two terms.
                By starting with 1 and 2, the first 10 terms will be:
                1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
                By considering the terms in the Fibonacci sequence whose values do not exceed four million,
                find the sum of the even-valued terms.

                TUR: Fibonacci dizisindeki her yeni terim kendisinden önceki iki terimin toplanmasıyla oluşturulur.
                1 ve 2 ile başlayınca ilk 10 terim aşağıdaki gibi olacaktır:
                1,2,3,5,8,13,21,34,55,89
                Değerlerin birinin 4 milyonu geçmemesini göz önünde bulundurarak dizideki çift sayıların toplamını
                bul.
              */
            int yeniTerim = 0, sonTerim = 2, sondanOncekiTerim = 1, ciftToplami = 2;
            while (yeniTerim < 4000000){
                yeniTerim = sonTerim + sondanOncekiTerim;
                sondanOncekiTerim = sonTerim;
                sonTerim = yeniTerim;

                if (yeniTerim % 2 == 0)
                {
                    ciftToplami += yeniTerim;
                }
            }
            Console.WriteLine(ciftToplami);
        }
    }
}
