using System;

namespace problem12
{
    class Program
    {
        static void Main(string[] args)
        {
            /*
             Project Euler Problem 12
             
            EN: The sequence of triangle numbers is generated by adding the natural numbers. 
            So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
            Let us list the factors of the first seven triangle numbers:
            1: 1
            3: 1,3
            6: 1,2,3,6
            10: 1,2,5,10
            15: 1,3,5,15
            21: 1,3,7,21
            28: 1,2,4,7,14,28
            We can see that 28 is the first triangle number to have over five divisors.
            What is the value of the first triangle number to have over five hundred divisors?
             
            TR: Üçgen sayılar doğal sayların sırayla toplnamasıyla oluşan sayılardır. 7. üçgen sayı 1+2+3+4+5+6+7 = 28'dir. İlk 10 sayı 1, 3, 6, 13, 15, 21, 28, 36, 45, 55 şeklindedir.
            28 sayısının 5'ten fazla böleni olan ilk üçgen sayı olduğunu görüyoruz buna göre 500'den fazla bölene sahip ilk üçgen sayı kaçtır ?
             */
            int ucgenSayimiz = 0, dogalSayimiz = 0, bolen = 1;
            while (true)
            {
                dogalSayimiz++; //1'den istediğimiz sayıya gidene kadar ekleme yapacağımız değişkenimiz.
                ucgenSayimiz += dogalSayimiz; //Üçgen sayı olması için sırasıyla 1'den son dogalSayimiz değerine kadar toplanarak giden ucgenSayımız.
                //Bölen kontrolü
                for (int i = 2; i <= ucgenSayimiz; i++)
                {
                    //Tüm pozitif sayılar 1'e bölünebildiği için dögüyü ikiden başlatıp bölen değişkenimizi 1'den başlatıyoruz ve her bölen olduğunda bölen değişkenimizi artırıyoruz.
                    if (ucgenSayimiz % i == 0)
                    {
                        bolen++;
                    }
                }
                //Bölen sayımız istediğimiz değere ulaştığında sayımızı yazdırıyoruz ve döngümüzü bitiriyoruz.
                if (bolen > 500)
                {
                    Console.WriteLine(ucgenSayimiz);
                    break;
                }
                bolen = 1; //Farklı sayıya geçeceğimiz için bölen değişkenini başlangıçtaki değerine eşitliyoruz.
            }
        }
    }
}
