# -*- coding: utf-8 -*-
"""problem9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xzEjw5BWmGzUCkK2PpwzURe9in5oGPZk
"""

import time

start = time.time()

primes = [2]

for i in range(3,2000000):
    check = True
    for j in range(2,i):
        
        if i%j == 0:
            check = False
            break
        
    if check:
        primes.append(i)

end = time.time()

process_time = round((end-start)/60,2)


print("This process took {} minutes".format(process_time))

print(sum(primes))

