"""
Project Euler Problem 2 

EN: Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.
 
TUR: Fibonacci dizisindeki her yeni terim kendisinden önceki iki terimin toplanmasıyla oluşturulur.
1 ve 2 ile başlayınca ilk 10 terim aşağıdaki gibi olacaktır:
1,2,3,5,8,13,21,34,55,89

Değerlerin birinin 4 milyonu geçmemesini göz önünde bulundurarak dizideki çift sayıların toplamını
bul.
"""

# Fibonacci dizimizi oluşturduk, bu dizi 1 ve 2 ile başlar
fibonacci = [1,2]

# Fibonacci dizimizin son değeri 4 milyondan küçük olduğu sürece
while fibonacci[-1] < 4000000:
    
    # Fibonacci dizimize yeni bir değer ekleyeceğiz
    # Bu değer son değerle sondan bir önceki değerin toplamı
    fibonacci.append(fibonacci[-1]+fibonacci[-2])

# Eğer terim 2 ye tam bölünüyorsa (çiftse)
# Onu diziye ekle
even_fibonacci = [term for term in fibonacci if term%2==0]

# Topla
sum_of_even_terms = sum(even_fibonacci)
